root = "."
tmp_dir = "build"
[build]
  cmd = "go build -o build/main"
  bin = "./build/main"
  args_bin = ["-task", "serve"]
  delay = 1000
  exclude_dir = ["build", "apps"]
  include_ext = ["go", "tpl", "tmpl", "html", "tsx"]
  exclude_regex = ["_test\\.go"]
