version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - apps:/app/apps
      - ./:/app
    tty: true
    links:
      - voicevox
      - admin
      - mongo

  voicevox:
    image: voicevox/voicevox_engine
    tty: true

  admin:
    build:
      context: ./apps/admin
      dockerfile: Dockerfile
    volumes:
      - ./apps/admin:/app
      - node_modules:/app/node_modules
    command: yarn dev
    tty: true

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./apps/mongodb/db:/data/db
      - ./apps/mongodb/configdb:/data/configdb

  mongo-express:
    image: mongo-express
    ports:
      - 3001:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_SERVER: mongo
    links:
      - mongo

volumes:
  # to ignore dir.
  apps:
  node_modules:
