version: '3.8'

services:
  voicevox:
    image: voicevox/voicevox_engine
    ports:
      - 50021:50021
    tty: true

  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - ./docker/redis/data:/data
