version: '3.8'

services:
  voicevox:
    image: voicevox/voicevox_engine
    tty: true

  redis:
    image: redis
    volumes:
      - ./docker/redis/data:/data

  minio:
    image: minio/minio
    ports:
      - 9001:9001
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password
      - MINIO_ADDRESS=:9000
      - MINIO_CONSOLE_ADDRESS=:9001
    volumes:
      - ./docker/minio/data:/data
    command: server /data
    tty: true
