version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./:/app
      - apps:/app/apps
    environment:
      - BUCKET=sample
    tty: true
    links:
      - voicevox
      - admin
      - redis
      - minio

  voicevox:
    image: voicevox/voicevox_engine
    tty: true

  admin:
    build:
      context: ./apps/admin
      dockerfile: Dockerfile
    volumes:
      - ./apps/admin:/app
      - node_modules:/app/node_modules
    command: pnpm dev
    tty: true

  redis:
    image: redis
    volumes:
      - ./apps/redis:/data

  minio:
    image: minio/minio
    ports:
      - 9001:9001
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password
    volumes:
      - ./apps/minio:/export
    entrypoint: sh
    command: -c "/opt/bin/minio server /export --address :9000 --console-address :9001"
    tty: true

volumes:
  # to ignore dir.
  apps:
  node_modules:
