version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    tty: true
    depends_on:
      - voicevox
      - redis

  # admin:
  #   build:
  #     context: .
  #     dockerfile: admin/Dockerfile
  #   ports:
  #     - 3000:3000
  #   tty: true

  voicevox:
    image: voicevox/voicevox_engine
    ports:
      - 50021:50021
    tty: true

  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - ./docker/redis/data:/data
