version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - .:/workspace:cached
      - apps:/app/apps
    env_file:
      - .env
    environment:
      - MINIO_BUCKET=sample
      - MINIO_HOST=minio:9000
      - REDIS_HOST=redis:6379
      - ADMIN_HOST=admin:3000
    tty: true
    links:
      - voicevox
      - admin
      - redis
      - minio

  voicevox:
    image: voicevox/voicevox_engine
    tty: true

  admin:
    build:
      context: ./apps/admin
      dockerfile: Dockerfile
    volumes:
      - .:/workspace:cached
      - node_modules:/workspace/apps/admin/node_modules
    command: pnpm dev
    tty: true

  redis:
    image: redis
    volumes:
      - ./apps/redis:/data

  minio:
    image: minio/minio
    ports:
      - 9001:9001
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password
      - MINIO_ADDRESS=:9000
      - MINIO_CONSOLE_ADDRESS=:9001
    volumes:
      - ./apps/minio:/data
    command: server /data
    tty: true

volumes:
  # to ignore dir.
  apps:
  node_modules:
