# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: '3'

env:
  REDIS_HOST: localhost:6379
  VOICEVOX_BASE_URL: http://localhost:50021

tasks:
  collect:
    desc: collect
    cmd: go run . collect

  serve:
    desc: start dev server
    cmd: go run -tags dev . serve

  openapi:
    desc: emit openapi
    cmd: go run . emit-openapi > ./admin/openapi.yaml
