# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: '3'

env:
  MINIO_BUCKET: sample
  MINIO_HOST: localhost:9000
  REDIS_HOST: localhost:6379
  VOICEVOX_BASE_URL: http://localhost:50021

tasks:
  serve:
    desc: start dev server
    cmd: go run -tags dev . serve

  collect:
    desc: collect
    cmd: go run . collect

  openapi:
    desc: emit openapi
    cmd: go run . emit-openapi > ./admin/openapi.yaml

  serve-prod:
    desc: serve
    cmd: speakit serve

  collect-prod:
    desc: collect
    cmd: speakit collect
