# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: '3'

tasks:
  collect:
    desc: collect
    cmd: go run . collect --redis localhost:6379 --voicevox localhost:50021

  serve:
    desc: start dev server
    cmd: go run -tags dev . serve --redis localhost:6379 --voicevox localhost:50021

  openapi:
    desc: emit openapi
    cmd: go run . emit-openapi > ./admin/openapi.yaml
