/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * Speakit API
 * OpenAPI spec version: 0.1.0
 */
import type { ApifeedsData } from './apifeedsData';

export interface Apifeeds {
  created?: string;
  data?: ApifeedsData;
  id?: string;
  modified?: string;
}
