/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * Speakit API
 * OpenAPI spec version: 0.1.0
 */
import type { ApifeedsWithMetadataData } from './apifeedsWithMetadataData';

export interface ApifeedsWithMetadata {
  created?: string;
  data?: ApifeedsWithMetadataData;
  id?: string;
  modified?: string;
}
