/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * Speakit API
 * OpenAPI spec version: 0.1.0
 */

export interface Apiprograms {
  content?: string;
  converted?: boolean;
  title?: string;
}
