/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * Speakit API
 * OpenAPI spec version: 0.1.0
 */
import type { Apiprograms } from './apiprograms';

export type Getapiprograms200 = {
  items?: Apiprograms[];
};
