/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * Speakit API
 * OpenAPI spec version: 0.1.0
 */

export * from './apifeeds';
export * from './feeds';
export * from './getapifeeds200';
export * from './getfeeds200';