/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * Speakit API
 * OpenAPI spec version: 0.1.0
 */

export * from './apiconvert';
export * from './apifeeds';
export * from './apifeedsData';
export * from './apifeedsWithMetadata';
export * from './apifeedsWithMetadataData';
export * from './apifetch';
export * from './apiprograms';
export * from './apiprogramsWithMetadata';
export * from './apiprogramsWithMetadataData';
export * from './feeds';
export * from './getapifeeds200';
export * from './getapiprograms200';
export * from './getfeeds200';