/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * Speakit API
 * OpenAPI spec version: 0.1.0
 */
import type { ProgramsWithMetadataData } from './programsWithMetadataData'

export interface ProgramsWithMetadata {
  created?: string
  data?: ProgramsWithMetadataData
  id?: string
  modified?: string
}
