/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * Speakit API
 * OpenAPI spec version: 0.1.0
 */
import type { FeedsWithMetadataData } from './feedsWithMetadataData'

export interface FeedsWithMetadata {
  created?: string
  data?: FeedsWithMetadataData
  id?: string
  modified?: string
}
