/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * Speakit API
 * OpenAPI spec version: 0.1.0
 */
import type { ProgramsWithMetadata } from './programsWithMetadata'

export type Getprograms200 = {
  items?: ProgramsWithMetadata[]
}
